version: "3.9"

services:
  db:
    image: postgres:12-alpine
    container_name: "splid_postgres_db"
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: "splid_app"
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    volumes:
      - ./:/app
    networks:
      - fullstack
    depends_on:
      - db
    init: true # to stop the container quickly

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge